openapi: 3.0.0
info:
  title: Quote API
  description: Get a random quote using quote API
  version: 0.0.1

servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /quote:
    get:
      responses:
        '200':
          description: Quote
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Quote:
      properties:
        quote:
          type: string
        author:
          type: string
      required: 
        - quote
        - author