openapi: 3.0.0
info:
  title: Word API
  description: Get a random word and its definition using quote API
  version: 0.0.1

servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /word:
    get:
      responses:
        '200':
          description: Definition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Definition'
components:
  schemas:
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
      required: 
        - word
        - definition